
CREATE TABLE IF NOT EXISTS usuarios(
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(50) DEFAULT NULL,
	apellido VARchar(50) DEFAULT NULL,
	email VARCHAR(100) DEFAULT NULL,
	password VARCHAR(50) DEFAULT NULL,
	api_token VARCHAR(100) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agendas(
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(50) DEFAULT NULL,
	id_usuario SERIAL
);

CREATE TABLE IF NOT EXISTS grupos(
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(50) DEFAULT NULL,
	id_agenda NUMERIC(11) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contactos(
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(50) DEFAULT NULL,
	apellido VARchar(50) DEFAULT NULL,
	email VARCHAR(100) DEFAULT NULL,
	numero_celular VARCHAR(100) DEFAULT NULL,
	numero_trabajo VARCHAR(100) DEFAULT NULL,
	direccion VARCHAR(100) DEFAULT NULL,
	agenda_id NUMERIC(11) DEFAULT NULL,
	grupo_id NUMERIC(11) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS imagenes(
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(100) DEFAULT NULL,
	link VARCHAR(200) DEFAULT NULL,
	contacto_id NUMERIC(11) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
